"""Donation comment

Revision ID: b50d373d6e07
Revises: 0cc4b51ddcc3
Create Date: 2023-10-04 10:13:50.188379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50d373d6e07'
down_revision = '0cc4b51ddcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation', 'comment')
    # ### end Alembic commands ###
